/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author gaby garcia
 */
public class ViewClientes extends javax.swing.JPanel {

    /**
     * Creates new form ViewClientes
     */
    public ViewClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_id_cliente = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        jtf_id_cliente = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_telefono = new javax.swing.JTextField();
        jtf_email = new javax.swing.JTextField();
        jtf_direccion = new javax.swing.JTextField();
        jl_telefono = new javax.swing.JLabel();
        jl_email = new javax.swing.JLabel();
        jl_direccion = new javax.swing.JLabel();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jbtn_agregar = new javax.swing.JButton();
        jbtn_editar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_primero = new javax.swing.JButton();
        jbtn_nuevo = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(51, 51, 51));
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(492, 374));

        jl_id_cliente.setBackground(new java.awt.Color(0, 0, 0));
        jl_id_cliente.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jl_id_cliente.setText("ID Cliente");

        jl_nombre.setBackground(new java.awt.Color(0, 0, 0));
        jl_nombre.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jl_nombre.setText("Nombre");

        jl_telefono.setBackground(new java.awt.Color(0, 0, 0));
        jl_telefono.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jl_telefono.setText("Telefono");

        jl_email.setBackground(new java.awt.Color(0, 0, 0));
        jl_email.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jl_email.setText("Email");

        jl_direccion.setBackground(new java.awt.Color(0, 0, 0));
        jl_direccion.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jl_direccion.setText("Dirección");

        jbtn_anterior.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_anterior.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbtn_anterior.setText("<<");
        jbtn_anterior.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_anterior.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_anterior.setPreferredSize(new java.awt.Dimension(200, 40));
        jbtn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_anteriorActionPerformed(evt);
            }
        });

        jbtn_siguiente.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_siguiente.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbtn_siguiente.setText(">>");
        jbtn_siguiente.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_siguiente.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_siguiente.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_ultimo.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_ultimo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbtn_ultimo.setText(">|");
        jbtn_ultimo.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_ultimo.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_ultimo.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_agregar.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_agregar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbtn_agregar.setText("Agregar");
        jbtn_agregar.setMaximumSize(new java.awt.Dimension(300, 40));
        jbtn_agregar.setMinimumSize(new java.awt.Dimension(300, 40));
        jbtn_agregar.setPreferredSize(new java.awt.Dimension(300, 40));
        jbtn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarActionPerformed(evt);
            }
        });

        jbtn_editar.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_editar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbtn_editar.setText("Editar");
        jbtn_editar.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_editar.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_editar.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_eliminar.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_eliminar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbtn_eliminar.setText("Eliminar");
        jbtn_eliminar.setMaximumSize(new java.awt.Dimension(300, 40));
        jbtn_eliminar.setMinimumSize(new java.awt.Dimension(300, 40));
        jbtn_eliminar.setPreferredSize(new java.awt.Dimension(300, 40));

        jbtn_primero.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_primero.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbtn_primero.setText("|<");
        jbtn_primero.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_primero.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_primero.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_nuevo.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_nuevo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbtn_nuevo.setText("Nuevo");
        jbtn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_nuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jbtn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_nuevo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtn_primero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_nombre)
                                    .addComponent(jl_id_cliente)
                                    .addComponent(jl_telefono)
                                    .addComponent(jl_email)
                                    .addComponent(jl_direccion))
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtf_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jtf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jtf_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jl_id_cliente)
                        .addGap(18, 18, 18)
                        .addComponent(jl_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jl_email)
                        .addGap(34, 34, 34)
                        .addComponent(jl_direccion)
                        .addGap(39, 39, 39)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_primero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_anteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_anteriorActionPerformed

    private void jbtn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_agregarActionPerformed

    private void jbtn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_nuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_editar;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JLabel jl_direccion;
    public javax.swing.JLabel jl_email;
    public javax.swing.JLabel jl_id_cliente;
    public javax.swing.JLabel jl_nombre;
    public javax.swing.JLabel jl_telefono;
    public javax.swing.JTextField jtf_direccion;
    public javax.swing.JTextField jtf_email;
    public javax.swing.JTextField jtf_id_cliente;
    public javax.swing.JTextField jtf_nombre;
    public javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables
}
