/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author gaby garcia
 */
public class ViewPeliculas extends javax.swing.JPanel {

    /**
     * Creates new form ViewPeliculas
     */
    public ViewPeliculas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_id_pelicula = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        jl_formato = new javax.swing.JLabel();
        jl_duracion = new javax.swing.JLabel();
        jl_descripcion = new javax.swing.JLabel();
        jtf_id_pelicula = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_duracion = new javax.swing.JTextField();
        jcb_formato = new javax.swing.JComboBox<>();
        jsp1_formato = new javax.swing.JScrollPane();
        jta_descripcion = new javax.swing.JTextArea();
        jbtn_primero = new javax.swing.JButton();
        jbtn_nuevo = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jbtn_agregar = new javax.swing.JButton();
        jbtn_editar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setMaximumSize(null);

        jl_id_pelicula.setBackground(new java.awt.Color(0, 0, 0));
        jl_id_pelicula.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jl_id_pelicula.setText("ID Película");

        jl_nombre.setBackground(new java.awt.Color(0, 0, 0));
        jl_nombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jl_nombre.setText("Nombre");

        jl_formato.setBackground(new java.awt.Color(0, 0, 0));
        jl_formato.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jl_formato.setText("Formato");

        jl_duracion.setBackground(new java.awt.Color(0, 0, 0));
        jl_duracion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jl_duracion.setText("Duración");

        jl_descripcion.setBackground(new java.awt.Color(0, 0, 0));
        jl_descripcion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jl_descripcion.setText("Descripción");

        jtf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombreActionPerformed(evt);
            }
        });

        jcb_formato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DVD", "Blue-Ray" }));

        jta_descripcion.setColumns(20);
        jta_descripcion.setRows(5);
        jsp1_formato.setViewportView(jta_descripcion);

        jbtn_primero.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_primero.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_primero.setText("|<");
        jbtn_primero.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_primero.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_primero.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_nuevo.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_nuevo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbtn_nuevo.setText("Nuevo");
        jbtn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_nuevoActionPerformed(evt);
            }
        });

        jbtn_anterior.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_anterior.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_anterior.setText("<<");
        jbtn_anterior.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_anterior.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_anterior.setPreferredSize(new java.awt.Dimension(200, 40));
        jbtn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_anteriorActionPerformed(evt);
            }
        });

        jbtn_siguiente.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_siguiente.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_siguiente.setText(">>");
        jbtn_siguiente.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_siguiente.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_siguiente.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_ultimo.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_ultimo.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_ultimo.setText(">|");
        jbtn_ultimo.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_ultimo.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_ultimo.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_agregar.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_agregar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbtn_agregar.setText("Agregar");
        jbtn_agregar.setMaximumSize(new java.awt.Dimension(300, 40));
        jbtn_agregar.setMinimumSize(new java.awt.Dimension(300, 40));
        jbtn_agregar.setPreferredSize(new java.awt.Dimension(300, 40));
        jbtn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarActionPerformed(evt);
            }
        });

        jbtn_editar.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_editar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbtn_editar.setText("Editar");
        jbtn_editar.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_editar.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_editar.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_eliminar.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_eliminar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbtn_eliminar.setText("Eliminar");
        jbtn_eliminar.setMaximumSize(new java.awt.Dimension(300, 40));
        jbtn_eliminar.setMinimumSize(new java.awt.Dimension(300, 40));
        jbtn_eliminar.setPreferredSize(new java.awt.Dimension(300, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_duracion)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jl_nombre)
                                .addComponent(jl_formato))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jl_id_pelicula))))
                    .addComponent(jl_descripcion))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtf_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jcb_formato, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtf_id_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtf_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsp1_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 412, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn_primero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn_nuevo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jbtn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jbtn_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_id_pelicula)
                    .addComponent(jtf_id_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombre)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_formato)
                    .addComponent(jcb_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jl_duracion)
                        .addGap(49, 49, 49)
                        .addComponent(jl_descripcion))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtf_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jsp1_formato, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_primero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nombreActionPerformed

    private void jbtn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_nuevoActionPerformed

    private void jbtn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_anteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_anteriorActionPerformed

    private void jbtn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_agregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_editar;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JComboBox<String> jcb_formato;
    public javax.swing.JLabel jl_descripcion;
    public javax.swing.JLabel jl_duracion;
    public javax.swing.JLabel jl_formato;
    public javax.swing.JLabel jl_id_pelicula;
    public javax.swing.JLabel jl_nombre;
    public javax.swing.JScrollPane jsp1_formato;
    public javax.swing.JTextArea jta_descripcion;
    public javax.swing.JTextField jtf_duracion;
    public javax.swing.JTextField jtf_id_pelicula;
    public javax.swing.JTextField jtf_nombre;
    // End of variables declaration//GEN-END:variables
}
